-- Certificate submission table and least-privilege RLS for the browser client.
create table if not exists public.certificate_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  age integer not null check (age between 1 and 120),
  class_name text not null,
  designation text not null,
  created_at timestamptz not null default now()
);

alter table public.certificate_submissions enable row level security;

-- Users may insert only their own submission.
drop policy if exists "authenticated users can insert own certificate request" on public.certificate_submissions;
create policy "authenticated users can insert own certificate request"
on public.certificate_submissions
for insert to authenticated
with check (auth.uid() = user_id);

-- Optional: users can read only their own submissions.
drop policy if exists "authenticated users can read own certificate requests" on public.certificate_submissions;
create policy "authenticated users can read own certificate requests"
on public.certificate_submissions
for select to authenticated
using (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant insert, select on public.certificate_submissions to authenticated;
