-- ============================================================
-- NSS VOLUNTEERS PORTAL - SUPABASE DATABASE SETUP
-- Run this entire file in Supabase SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- PROFILES
-- One profile row per authenticated user.
-- ------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  class text not null default '',
  roll_no text not null default '',
  phone text not null default '',
  email text not null default '',
  father_name text not null default '',
  mother_name text not null default '',
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_roll_no_format
    check (roll_no = '' or roll_no ~ '^UA-[A-Za-z0-9]+-[A-Za-z0-9]+$')
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles for select to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles for insert to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- ------------------------------------------------------------
-- CERTIFICATES
-- A certificate generated by a user.
-- ------------------------------------------------------------
create table if not exists public.certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  certificate_key text not null,
  certificate_title text not null,
  generated_at timestamptz not null default now(),
  unique(user_id, certificate_key)
);

alter table public.certificates enable row level security;

drop policy if exists "Users can view own certificates" on public.certificates;
create policy "Users can view own certificates"
on public.certificates for select to authenticated
using (auth.uid() = user_id);

-- Inserts are deliberately restricted to the RPC below.
-- Users cannot directly insert certificates from the browser.

-- ------------------------------------------------------------
-- CERTIFICATE ATTEMPTS
-- Stores the failed-code lockout until timestamp.
-- ------------------------------------------------------------
create table if not exists public.certificate_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  certificate_key text not null,
  locked_until timestamptz,
  last_failed_at timestamptz not null default now(),
  unique(user_id, certificate_key)
);

alter table public.certificate_attempts enable row level security;

drop policy if exists "Users can view own certificate attempts" on public.certificate_attempts;
create policy "Users can view own certificate attempts"
on public.certificate_attempts for select to authenticated
using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- PRIVATE PHOTO STORAGE
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('student-photos', 'student-photos', false)
on conflict (id) do nothing;

drop policy if exists "Users can upload own student photo" on storage.objects;
create policy "Users can upload own student photo"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'student-photos'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Users can update own student photo" on storage.objects;
create policy "Users can update own student photo"
on storage.objects for update to authenticated
using (
  bucket_id = 'student-photos'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Users can delete own student photo" on storage.objects;
create policy "Users can delete own student photo"
on storage.objects for delete to authenticated
using (
  bucket_id = 'student-photos'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Users can read own student photo" on storage.objects;
create policy "Users can read own student photo"
on storage.objects for select to authenticated
using (
  bucket_id = 'student-photos'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

-- ------------------------------------------------------------
-- SECURE CERTIFICATE RPC
--
-- IMPORTANT: Certificate codes are intentionally NOT stored in
-- a public table. They are checked inside this server-side
-- SECURITY DEFINER function.
--
-- Change the three codes below before real deployment if needed.
-- ------------------------------------------------------------
create or replace function public.generate_certificate(
  p_certificate_key text,
  p_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_expected text;
  v_title text;
  v_locked_until timestamptz;
  v_existing public.certificates;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  if p_certificate_key not in ('certificate-1','certificate-2','certificate-3') then
    raise exception 'Invalid certificate';
  end if;

  -- ==========================================================
  -- FUTURE CERTIFICATE CONFIG:
  -- Add/change certificate keys, titles and codes here.
  -- Keep the codes server-side; do NOT put secret codes in
  -- React source code.
  -- ==========================================================
  case p_certificate_key
    when 'certificate-1' then
      v_expected := '99';
      v_title := 'NSS Certificate 1';
    when 'certificate-2' then
      v_expected := '78';
      v_title := 'NSS Certificate 2';
    when 'certificate-3' then
      v_expected := '23';
      v_title := 'NSS Certificate 3';
  end case;

  select *
  into v_existing
  from public.certificates
  where user_id = v_user
    and certificate_key = p_certificate_key
  limit 1;

  if found then
    return jsonb_build_object(
      'status','already_generated',
      'certificate_id',v_existing.id,
      'generated_at',v_existing.generated_at
    );
  end if;

  select locked_until
  into v_locked_until
  from public.certificate_attempts
  where user_id = v_user
    and certificate_key = p_certificate_key;

  if v_locked_until is not null and v_locked_until > now() then
    return jsonb_build_object(
      'status','locked',
      'locked_until',v_locked_until
    );
  end if;

  if p_code is distinct from v_expected then
    insert into public.certificate_attempts(
      user_id, certificate_key, locked_until, last_failed_at
    )
    values (
      v_user, p_certificate_key, now() + interval '24 hours', now()
    )
    on conflict (user_id, certificate_key)
    do update set
      locked_until = now() + interval '24 hours',
      last_failed_at = now();

    return jsonb_build_object(
      'status','wrong_code',
      'locked_until',now() + interval '24 hours'
    );
  end if;

  insert into public.certificates(
    user_id, certificate_key, certificate_title
  )
  values (
    v_user, p_certificate_key, v_title
  )
  on conflict (user_id, certificate_key) do nothing
  returning * into v_existing;

  return jsonb_build_object(
    'status','generated',
    'certificate_id',v_existing.id,
    'certificate_key',p_certificate_key,
    'certificate_title',v_title,
    'generated_at',v_existing.generated_at
  );
end;
$$;

revoke all on function public.generate_certificate(text,text) from public;
grant execute on function public.generate_certificate(text,text) to authenticated;

-- ------------------------------------------------------------
-- OPTIONAL: Create profile row automatically on signup.
-- The website still requires the details form to be completed.
-- ------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, coalesce(new.email, ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
